### ISSUE TITLE
Nuke Command Fix

### ISSUE THREAD

**Issue by Trip-kun** [frc5183/Oatmeal#6]
The nuke command frequently runs into ratelimit issues while operating because it quickly spams requests to delete messages. The bot should limit itself to prevent a ratelimit by waiting every few messages (as specified in discord ratelimit) and then starting again.

**Comment by Baconing** [comment]
There is a [deleteMessages](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/entities/TextChannel.html#deleteMessages(java.util.Collection)) method for bulk deleting that uses a List<Messages>

**Comment by Trip-kun** [comment]
This seems like a perfect solution, and I think it'll line up perfectly with the getMessages that we call, simplifying the entire system
