### ISSUE TITLE
Remove "Trip-Only" commands

### ISSUE THREAD

**Issue by Baconing** [frc5183/Oatmeal#9]
Doesn't seem to belong considering it is an open source project with multiple different contributors and potentially running instances.

Maybe we just migrate all Trip-Only commands into the Owner(s) functionality, as well as potentially having an array of user id's as owners in the bot's config file.

**Comment by Trip-kun** [comment]
Agreed. Those were really just a legacy method for when my machine borked and I needed a forceful reboot remotely.

The useful commands should be migrated to Owner(s), while the rest can be safely dropped.

**Comment by Baconing** [comment]
https://github.com/frc5183/Oatmeal/commit/1f3f719fc96535adc6b0f853a8dc1f4f75abb4b0 done
